# mapping_epoxy.yaml - 环氧树脂CG映射配置示例

site-types:
  Head:
    index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
    x-weight: [12, 12, 1, 1, 12, 12, 12, 1, 1, 1, 1, 1, 1, 1]
  Mid:
    index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
    x-weight: [12, 12, 1, 1, 12, 12, 12, 1, 1, 1, 1, 1, 1]
  End:
    index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
    x-weight: [1, 12, 12, 1, 1, 12, 12, 12, 1, 1, 1, 1, 1, 1]

config:
  - anchor: 0
    repeat: 1
    offset: 132
    sites:
      - [Head, 0]
      - [Mid, 14]
      - [End, 118]